name: HarnessMobile
options:
  bundleIdPrefix: com.harness
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    DEVELOPMENT_TEAM: C64DYYG928
packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.4.1
  Highlightr:
    url: https://github.com/raspu/Highlightr
    from: 2.2.0
  Soto:
    url: https://github.com/soto-project/soto
    from: 7.0.0
targets:
  HarnessMobile:
    type: application
    platform: iOS
    sources:
      - path: HarnessMobile
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.harness.mobile
        INFOPLIST_FILE: HarnessMobile/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: MarkdownUI
      - package: Highlightr
      - product: SotoS3
        package: Soto
  HarnessMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HarnessMobileTests
    dependencies:
      - target: HarnessMobile
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.harness.mobile.tests
        GENERATE_INFOPLIST_FILE: YES
schemes:
  HarnessMobile:
    build:
      targets:
        HarnessMobile: all
    test:
      targets:
        - HarnessMobileTests
